[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/2022/09/16/les-journees-dete-dutopia/index.html"
to = "/actualites/2022-09-16-les-journees-dete-dutopia/"

[[redirects]]
from = "/fr/index.html"
to = "/"

[[redirects]]
from = "/actualites/2022/09/23/rencontres-de-lecologie-urbaine-de-la-decroissance-et-de-lanthropocene/index.html"
to = "/actualites/2022-09-23-rencontres-de-lecologie-urbaine-de-la-decroissance-et-de-lanthropocene/"

[[redirects]]
from = "/fr/lobservatoire/membres/index.html"
to = "/lobservatoire/membres/"

[[redirects]]
from = "/fr/politique-de-confidentialite/index.html"
to = "/politique-de-confidentialite/"

[[redirects]]
from = "/fr/veille-scientifique/articles/index.html"
to = "/veille-scientifique/articles/"

[[redirects]]
from = "/fr/lobservatoire/membres/equipe-editoriale/index.html"
to = "/lobservatoire/membres/equipe-editoriale/"

[[redirects]]
from = "/actualites/2022/11/14/retour-sur-les-10-ans-de-linstitut-momentum/index.html"
to = "/actualites/2022-11-14-retour-sur-les-10-ans-de-linstitut-momentum/"

[[redirects]]
from = "/fr/actualites/index.html"
to = "/actualites/"

[[redirects]]
from = "/actualites/2022/11/14/mondes-en-decroissance-la-revue-portee-par-lopcd/index.html"
to = "/actualites/2022-11-14-mondes-en-decroissance-la-revue-portee-par-lopcd/"

[[redirects]]
from = "/fr/lobservatoire/index.html"
to = "/lobservatoire/"

[[redirects]]
from = "/fr/plan-du-site/index.html"
to = "/plan-du-site/"

[[redirects]]
from = "/actualites/2022/12/29/le-chemin-de-la-decroissance-le-reve-de-la-post-croissance/index.html"
to = "/actualites/2022-12-29-le-chemin-de-la-decroissance-le-reve-de-la-post-croissance/"

[[redirects]]
from = "/fr/accessibilite/index.html"
to = "/accessibilite/"

[[redirects]]
from = "/fr/espace-presse/index.html"
to = "/espace-presse/"

[[redirects]]
from = "/fr/test/index.html"
to = "/test/"

[[redirects]]
from = "/fr/veille-scientifique/index.html"
to = "/veille-scientifique/"

[[redirects]]
from = "/fr/lobservatoire/qui-sommes-nous/index.html"
to = "/lobservatoire/qui-sommes-nous/"

[[redirects]]
from = "/fr/projets/index.html"
to = "/projets/"

[[redirects]]
from = "/fr/veille-scientifique/theses-et-memoires/index.html"
to = "/veille-scientifique/theses-et-memoires/"

[[redirects]]
from = "/actualites/2022/03/10/conferences-de-lancement/index.html"
to = "/actualites/2022-03-10-conferences-de-lancement/"

[[redirects]]
from = "/fr/mentions-legales/index.html"
to = "/mentions-legales/"

[[redirects]]
from = "/fr/veille-scientifique/livres/index.html"
to = "/veille-scientifique/livres/"

[[redirects]]
from = "/actualites/2022/11/25/lettre-n1/index.html"
to = "/actualites/2022-11-25-lettre-n1/"

[[redirects]]
from = "/actualites/2022/09/23/celebration-du-50e-anniversaire-du-rapport-meadows-1er-et-2-decembre-2022/index.html"
to = "/actualites/2022-09-23-celebration-du-50e-anniversaire-du-rapport-meadows-1er-et-2-decembre-2022/"

[[redirects]]
from = "/fr/lobservatoire/charte/index.html"
to = "/lobservatoire/charte/"

